import { afterEach, describe, expect, it, vi } from 'vitest';

import { createGitHubBranchAndPr } from '../adapters/github-pr';

afterEach(() => {
  vi.restoreAllMocks();
  vi.unstubAllGlobals();
});

describe('createGitHubBranchAndPr', () => {
  it('creates branch and pull request with github api', async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ object: { sha: 'abc123' } }), {
          status: 200,
          headers: { 'content-type': 'application/json' }
        })
      )
      .mockResolvedValueOnce(
        new Response(JSON.stringify({ ref: 'refs/heads/feature/test' }), {
          status: 201,
          headers: { 'content-type': 'application/json' }
        })
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            html_url: 'https://github.com/acme/jarvis/pull/42',
            number: 42,
            head: { ref: 'feature/test' },
            base: { ref: 'main' }
          }),
          {
            status: 201,
            headers: { 'content-type': 'application/json' }
          }
        )
      );
    vi.stubGlobal('fetch', fetchMock);

    const result = await createGitHubBranchAndPr(
      {
        token: 'ghs_test',
        owner: 'acme',
        repo: 'jarvis'
      },
      {
        branchName: 'feature/test',
        title: 'Automated update',
        body: 'Generated by code-loop'
      }
    );

    expect(result.url).toBe('https://github.com/acme/jarvis/pull/42');
    expect(result.number).toBe(42);
    expect(fetchMock).toHaveBeenCalledTimes(3);
  });

  it('fails fast when token is missing', async () => {
    await expect(
      createGitHubBranchAndPr(
        {
          owner: 'acme',
          repo: 'jarvis'
        },
        {
          branchName: 'feature/test',
          title: 'Automated update',
          body: 'Generated by code-loop'
        }
      )
    ).rejects.toThrow('github_token_missing');
  });

  it('returns permission failure on github auth errors', async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(JSON.stringify({ message: 'Bad credentials' }), {
        status: 401,
        headers: { 'content-type': 'application/json' }
      })
    );
    vi.stubGlobal('fetch', fetchMock);

    await expect(
      createGitHubBranchAndPr(
        {
          token: 'invalid',
          owner: 'acme',
          repo: 'jarvis'
        },
        {
          branchName: 'feature/test',
          title: 'Automated update',
          body: 'Generated by code-loop'
        }
      )
    ).rejects.toThrow('github_api_error:401');
  });
});
